Api 23234 request logging
department-of-veterans-affairs/lighthouse-master-patient-index pull request #35
Opened 2023-01-31 18:55 UTC by amizan8653-va

Addresses [API-23234](https://vajira.max.gov/browse/API-23234)
- adds the ability to turn on request level logging 
- by default, request level logging is off
- maintains backwards compatibility with codebases using old interface of this library
- if used, will log requests with a request id so that the story of what went wrong with a request can be found by searching for a specific id in the log

2023-02-01 14:25 UTC, bschofield-va requested changes
This is not the way to add this functionality. This implementation makes a SOAP client library drag in all sorts of _server components that are automatically configured_ ... whether you want them or not.

The more appropriate solution would be to design a generic "interceptor" concept that provides no implementation but allows any user of the library to inject whatever they want... including encrypted logging.

You could consider adding a single "request/response" inspector or one per request/response type.

E.g.
```
class SoapMasterPatientIndexClient {

   @Builder.Default  Consumer<PRPAIN201309UV02> inspector1309 = doNothing();
   @Builder.Default Consumer<PRPAIN201310UV02> inspector1310 = doNothing();
   ...
   
}
```

Then simply call the inspector where appropriate
```
    var mpi1309RequestBody =
         GetCorrespondingIdsRequest1309Creator.builder()
             .config(config)
             .asSoapRequest();
    inspector1309.accept(mpi1309RequestBody)
 ```
 
 The inspectors are never null, there is never in decision to make from the client code perspective. This becomes much more simple _while_ being more flexible.

2023-02-01 22:41 UTC, jhulbert-va submitted a review, later dismissed

2023-02-01 22:44 UTC, bschofield-va commented
yo dawg ... where the test that verifies these inceptors are called?

2023-02-02 17:09 UTC, amizan8653-va commented
> yo dawg ... where the test that verifies these inceptors are called?

Tests added now but... they doesn't get called. I added them just now without the `@EnabledIfSystemProperty(named = "interactive", matches = "true")` annotation. Doing it like that, they ran locally & passed. But then failed on Jenkins with a connection refused exception:

![image](https://user-images.githubusercontent.com/101663807/216393253-76cae177-4fe3-4ee4-9446-7be748fb9ab5.png)

If I go and add the `@EnabledIfSystemProperty(named = "interactive", matches = "true")` to my tests, then they get skipped both locally & on jenkins. They get skipped just like all of the tests in `SoapMasterPatientIndexClientTest`

Is there anywhere the tests in SoapMasterPatientIndexClientTest end up actually running?

2023-02-02 19:34 UTC, bschofield-va approved these changes

2023-02-02 19:34 UTC, merged